'use client';import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';import {get,post,put,patch,del} from '@/lib/api';import {Card,Button,PageHeader,Skeleton,ErrorState,Dialog} from './ui';import type {Product,Page,PickList,VendorProduct} from '@/types';import {useState} from 'react';import {CheckCircle2,PackageCheck,AlertTriangle,Search,Plus,RotateCcw} from 'lucide-react';
export function AdminDashboard(){const d=useQuery({queryKey:['admin-dashboard'],queryFn:()=>get<{ordersToday:number;lowStockCount:number;activeProducts:number;totalOrders:number}>('/admin/dashboard')});const orders=useQuery({queryKey:['admin-orders',0],queryFn:()=>get<Page<any>>('/admin/orders?page=0&size=8')});if(d.isLoading||orders.isLoading)return <><Skeleton className="h-10 w-60"/><div className="mt-7 grid gap-4 md:grid-cols-3"><Skeleton className="h-28"/><Skeleton className="h-28"/><Skeleton className="h-28"/></div></>;if(d.isError)return <ErrorState message={(d.error as Error).message} onRetry={()=>d.refetch()}/>;if(orders.isError)return <ErrorState message={(orders.error as Error).message} onRetry={()=>orders.refetch()}/>;return <><PageHeader title="Operations overview" subtitle="A fast read on today's marketplace health."/><div className="grid gap-4 md:grid-cols-3"><Metric title="Orders today" value={d.data?.ordersToday||0} hint="created since midnight"/><Metric title="Low stock" value={d.data?.lowStockCount||0} hint="≤ 5 units" danger={(d.data?.lowStockCount||0)>0}/><Metric title="Active products" value={d.data?.activeProducts||0} hint={`${d.data?.totalOrders||0} total orders`}/></div><Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Recent orders</h2><p className="text-sm text-gray-500">Newest orders across all stores.</p></div></div><Table headers={['Order','Customer','Total','Status','Created']} rows={(orders.data?.content||[]).map(o=>[`#${o.id}`,o.userEmail,`₹${Number(o.totalAmount).toLocaleString('en-IN')}`,<Status key="s" value={o.status}/>,new Date(o.createdAt).toLocaleString()])}/></Card></>}
function Metric({title,value,hint,danger}:{title:string;value:number;hint:string;danger?:boolean}){return <Card className="p-5"><div className="text-sm font-semibold text-gray-500">{title}</div><div className="mt-2 flex items-end gap-2"><div className="text-3xl font-black">{value}</div>{danger&&<AlertTriangle className="mb-1 text-red-500" size={18}/>}</div><div className="mt-1 text-xs text-gray-400">{hint}</div></Card>}
function Status({value}:{value:string}){return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${value==='DELIVERED'?'bg-green-100 text-green-700':value==='CANCELLED'?'bg-red-100 text-red-700':'bg-gray-100 text-gray-700'}`}>{value.replaceAll('_',' ')}</span>}
export function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wider text-gray-500"><tr>{headers.map(h=><th key={h} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-line">{rows.map((r,i)=><tr key={i} className="hover:bg-gray-50">{r.map((c,j)=><td key={j} className="px-5 py-4">{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="p-10 text-center text-sm text-gray-400">No records found.</div>}</div>}
export function AdminOrders(){const [page,setPage]=useState(0);const q=useQuery({queryKey:['admin-orders',page],queryFn:()=>get<Page<any>>(`/admin/orders?page=${page}&size=20`)});const qc=useQueryClient();const m=useMutation({mutationFn:({id,status}:{id:number;status:string})=>put(`/admin/orders/${id}/status`,{status}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-orders']})});return <><PageHeader title="All orders" subtitle="Paginated operational view across stores."/><Card><div className="p-5"><div className="text-sm text-gray-500">{q.data?.totalElements||0} total orders</div></div>{q.isLoading?<div className="space-y-3 p-5"><Skeleton className="h-12"/><Skeleton className="h-12"/></div>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<Table headers={['Order','Customer','Total','Status','Created','Update']} rows={(q.data?.content||[]).map(o=>[`#${o.id}`,o.userEmail,`₹${Number(o.totalAmount).toLocaleString('en-IN')}`,<Status key="s" value={o.status}/>,new Date(o.createdAt).toLocaleString(),<select key="x" disabled={m.isPending} defaultValue={o.status} onChange={e=>m.mutate({id:o.id,status:e.target.value})} className="rounded-lg border px-2 py-1 text-xs">{['PLACED','PACKED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select>])}/>}<div className="flex justify-between border-t p-4"><Button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="py-2 text-sm text-gray-500">Page {page+1} / {q.data?.totalPages||1}</span><Button disabled={!q.data||page+1>=q.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></Card></>}
export function AdminProducts(){const [search,setSearch]=useState('');const [page,setPage]=useState(0);const [editing,setEditing]=useState<Product|null>(null);const q=useQuery({queryKey:['products',search,page],queryFn:()=>get<Page<Product>>(`/admin/products?page=${page}&size=20${search?`&q=${encodeURIComponent(search)}`:''}`)});function updateSearch(v:string){setSearch(v);setPage(0)}return <><PageHeader title="Products" subtitle="Catalog visibility plus verified admin mutations." action={<Button onClick={()=>setEditing({id:0,name:'',categoryId:1,price:0,salePrice:0,stock:0,rating:0,isFeatured:false,reviewCount:0,active:true})}><Plus size={16}/> Create product</Button>}/><div className="mb-4 flex items-center gap-2 rounded-xl border bg-white px-3 py-2 md:max-w-md"><Search size={17}/><input value={search} onChange={e=>updateSearch(e.target.value)} placeholder="Search products…" className="w-full outline-none"/></div><Card>{q.isLoading?<div className="p-5"><Skeleton className="h-12"/></div>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<><div className="px-5 pt-5 text-sm text-gray-500">{q.data?.totalElements||0} total products{search?` matching “${search}”`:''}</div><Table headers={['Product','Barcode','Price','Stock','Featured','Action']} rows={(q.data?.content||[]).map(p=>[<div key="n"><b>{p.name}</b><div className="text-xs text-gray-400">#{p.id}</div></div>,p.barcode||'—',`₹${Number(p.effectivePrice??p.salePrice??p.price).toFixed(2)}`,<span key="st" className={p.stock<=5?'font-bold text-red-600':''}>{p.stock}</span>,p.isFeatured?'Yes':'No',<ProductActions key="a" product={p} onEdit={()=>setEditing(p)} refresh={()=>q.refetch()}/>])}/><div className="flex justify-between border-t p-4"><Button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="py-2 text-sm text-gray-500">Page {page+1} / {q.data?.totalPages||1}</span><Button disabled={!q.data||page+1>=q.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></>}</Card>{editing&&<ProductModal product={editing} close={()=>setEditing(null)} refresh={()=>q.refetch()}/>}</>}
function ProductActions({product,onEdit,refresh}:{product:Product;onEdit:()=>void;refresh:()=>void}){const qc=useQueryClient();const m=useMutation({mutationFn:(kind:'reactivate'|'delete')=>kind==='reactivate'?patch(`/admin/products/${product.id}/reactivate`):del(`/admin/products/${product.id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:['products']});refresh()}});return <div className="flex flex-wrap gap-2"><button disabled={!product.active} onClick={onEdit} className="font-semibold text-leaf disabled:opacity-40">Edit</button>{!product.active?<button disabled={m.isPending} onClick={()=>m.mutate('reactivate')} className="rounded-lg border px-2 py-1 text-xs font-semibold">Reactivate</button>:<button disabled={m.isPending} onClick={()=>{if(confirm('Delete this product?'))m.mutate('delete')}} className="rounded-lg border border-red-200 px-2 py-1 text-xs font-semibold text-red-600">Delete</button>}</div>}
function ProductModal({product,close,refresh}:{product:Product;close:()=>void;refresh:()=>void}){
 const [form,setForm]=useState({name:product.name,description:product.description||'',categoryId:String(product.categoryId),price:String(product.price),salePrice:String(product.salePrice),unit:product.unit||'',stock:String(product.stock),isFeatured:product.isFeatured});
 const errors={name:form.name.trim().length<2?'Name must be at least 2 characters':'',categoryId:Number(form.categoryId)>0?'':'Category is required',price:Number(form.price)>=0&&form.price!==''?'':'Price must be 0 or greater',salePrice:Number(form.salePrice)>=0&&form.salePrice!==''?'':'Sale price must be 0 or greater',stock:Number(form.stock)>=0&&form.stock!==''?'':'Stock must be 0 or greater'};
 const valid=Object.values(errors).every(x=>!x);
 const m=useMutation({mutationFn:()=>product.id?put(`/admin/products/${product.id}`,{...form,categoryId:Number(form.categoryId),price:Number(form.price),salePrice:Number(form.salePrice),stock:Number(form.stock),isFeatured:form.isFeatured}):post('/admin/products',{...form,categoryId:Number(form.categoryId),price:Number(form.price),salePrice:Number(form.salePrice),stock:Number(form.stock),isFeatured:form.isFeatured}),onSuccess:()=>{refresh();close()}});
 const field=(k:string,label:string)=><label key={k} className="text-sm font-semibold">{label}<input value={(form as any)[k]} aria-invalid={!!(errors as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="focus-ring mt-1 w-full rounded-xl border border-line px-3 py-2 theme-surface theme-text"/>{(errors as any)[k]&&<span className="mt-1 block text-xs font-medium text-red-700">{(errors as any)[k]}</span>}</label>;
 return <Dialog open title={`${product.id?'Edit':'Create'} product`} onClose={close} className="max-w-xl"><div className="max-h-[90vh] overflow-auto p-6"><div className="flex justify-between"><h2 id="dialog-title" className="text-xl font-black">{product.id?'Edit':'Create'} product</h2><button type="button" aria-label="Close product dialog" onClick={close} className="focus-ring text-xl">×</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{[['name','Name'],['categoryId','Category ID'],['price','Price'],['salePrice','Sale price'],['unit','Unit'],['stock','Stock']].map(([k,l])=>field(k,l))}<label className="text-sm font-semibold md:col-span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="focus-ring mt-1 w-full rounded-xl border border-line px-3 py-2 theme-surface theme-text"/></label><label className="flex gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isFeatured} onChange={e=>setForm({...form,isFeatured:e.target.checked})}/> Featured</label></div>{m.error&&<p className="mt-4 text-sm text-red-700" role="alert">{(m.error as Error).message}</p>}<div className="mt-6 flex justify-end gap-2"><button onClick={close} className="focus-ring rounded-xl border border-line px-4 py-2">Cancel</button><Button disabled={!valid||m.isPending} onClick={()=>m.mutate()}>{m.isPending?'Saving…':'Save product'}</Button></div></div></Dialog>}

export function WarehouseQueue(){
  const q=useQuery({queryKey:['pick-lists'],queryFn:()=>get<PickList[]>('/warehouse/pick-lists')});
  return <>
    <PageHeader title="Pick queue" subtitle="Oldest work first. Scan, pick, complete."/>
    {q.isLoading?<div className="space-y-3"><Skeleton className="h-28"/><Skeleton className="h-28"/></div>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<div className="grid gap-4">
      {(q.data||[]).map(p=><Card key={p.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-gray-400">Pick list #{p.id}</div><div className="mt-1 text-xl font-black">Order #{p.orderId}</div><div className="mt-1 text-sm text-gray-500">{p.items.length} line items · Store #{p.storeId}</div></div><a href={`/warehouse/pick-lists/${p.id}`} className="rounded-xl bg-ink px-4 py-2.5 text-sm font-bold text-white">Open pick list</a></div></Card>)}
      {!q.data?.length&&<Card className="p-8 text-center text-sm text-gray-500">No pending pick lists.</Card>}
    </div>}
    <Card className="mt-6 p-5"><h2 className="font-black">Inbound stock</h2><p className="mt-1 text-sm text-gray-500">Vendor replenishment is now handled through first-party Purchase Orders. Receive and verify inbound stock from the Purchase Orders workspace.</p><a href="/warehouse/purchase-orders" className="mt-4 inline-flex rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">Open purchase orders</a></Card>
  </>
}
export function PickDetail({id}:{id:number}){const qc=useQueryClient();const q=useQuery({queryKey:['pick',id],queryFn:async()=>{const all=await get<PickList[]>('/warehouse/pick-lists');return all.find(x=>x.id===id)||null}});const [barcode,setBarcode]=useState('');const pick=useMutation({mutationFn:({itemId,code}:{itemId:number;code:string})=>put(`/warehouse/pick-lists/${id}/items/${itemId}/pick`,{scannedBarcode:code}),onSuccess:()=>{setBarcode('');qc.invalidateQueries({queryKey:['pick',id]});qc.invalidateQueries({queryKey:['pick-lists']})}});const complete=useMutation({mutationFn:()=>put(`/warehouse/pick-lists/${id}/complete`),onSuccess:()=>{qc.invalidateQueries({queryKey:['pick',id]});qc.invalidateQueries({queryKey:['pick-lists']})}});if(q.isLoading)return <Skeleton className="h-40"/>;if(q.isError)return <ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>;if(!q.data)return <Card className="p-8">Pick list not found.</Card>;const done=q.data.items.every(x=>x.picked);return <><PageHeader title={`Pick list #${id}`} subtitle={`Order #${q.data.orderId} · ${q.data.status}`}/><div className="grid gap-4">{q.data.items.map(i=><Card key={i.id} className={`p-5 ${i.picked?'border-green-200 bg-green-50':''}`}><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex-1"><div className="text-lg font-black">{i.productName}</div><div className="mt-1 text-sm text-gray-500">Qty {i.quantity} · Barcode <b>{i.barcode}</b></div></div>{i.picked?<div className="flex items-center gap-2 font-bold text-green-700"><CheckCircle2/> Picked</div>:<div className="flex w-full gap-2 md:w-auto"><input value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="Scan barcode" className="focus-ring w-full rounded-xl border px-3 py-2 md:w-52"/><Button disabled={pick.isPending||!barcode} onClick={()=>pick.mutate({itemId:i.id,code:barcode})}>{pick.isPending?'Checking…':'Confirm pick'}</Button></div>}</div>{pick.error&&<p className="mt-2 text-sm text-red-600">{(pick.error as Error).message}</p>}</Card>)}<Card className="flex items-center justify-between p-5"><div><b>{done?'Ready to complete':'Complete when every line is picked'}</b></div><Button disabled={!done||complete.isPending} onClick={()=>complete.mutate()}>{complete.isPending?'Completing…':'Complete pick list'}</Button></Card></div></>}
// WarehouseStock/QuantityAdjust removed — the Stock page is now its own
// file at app/warehouse/stock/page.tsx (same treatment as the Vendors
// screen: dedicated file, search+picker modal, toast feedback) rather
// than a component here.
export function VendorDashboard(){const q=useQuery({queryKey:['vendor-products'],queryFn:()=>get<VendorProduct[]>('/vendor/products')});if(q.isLoading)return <Skeleton className="h-40"/>;if(q.isError)return <ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>;const ps=q.data||[];return <><PageHeader title="Vendor overview" subtitle="Quick-glance status of your linked products."/><div className="grid gap-4 md:grid-cols-3"><Metric title="Products" value={ps.length} hint="linked to your vendor"/><Metric title="In stock" value={ps.filter(p=>p.stock>0&&p.active).length} hint="active and available"/><Metric title="Out of stock" value={ps.filter(p=>p.stock===0||!p.active).length} hint="needs attention" danger={ps.some(p=>p.stock===0||!p.active)}/></div></>}
export function VendorProducts(){const q=useQuery({queryKey:['vendor-products'],queryFn:()=>get<VendorProduct[]>('/vendor/products')});const qc=useQueryClient();const m=useMutation({mutationFn:({id,price,salePrice,stock}:{id:number;price:number;salePrice:number;stock:number})=>put(`/vendor/products/${id}`,{price,salePrice,stock}),onSuccess:()=>qc.invalidateQueries({queryKey:['vendor-products']})});const headers=['Product','Barcode','Price','Sale price','Stock','Status','Save'];const data=q.data||[];return <><PageHeader title="My products" subtitle="Only products linked to your vendor account are returned."/><Card className="overflow-hidden">{q.isLoading?<Skeleton className="m-5 h-14"/>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wider text-gray-500"><tr>{headers.map(h=><th key={h} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-line">{data.map(p=><VendorRow key={p.productId} p={p} m={m}/>)}</tbody></table>{!data.length&&<div className="p-10 text-center text-sm text-gray-400">No records found.</div>}</div>}</Card></>}
function VendorRow({p,m}:any){const [f,setF]=useState({price:String(p.price),salePrice:String(p.salePrice),stock:String(p.stock)});return <tr className="hover:bg-gray-50"><td className="px-5 py-4 font-bold">{p.name}</td><td className="px-5 py-4">{p.barcode||'—'}</td><td className="px-5 py-4"><input className="w-24 rounded-lg border px-2 py-1" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></td><td className="px-5 py-4"><input className="w-24 rounded-lg border px-2 py-1" value={f.salePrice} onChange={e=>setF({...f,salePrice:e.target.value})}/></td><td className="px-5 py-4"><input className="w-20 rounded-lg border px-2 py-1" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/></td><td className="px-5 py-4">{p.active&&p.stock>0?<span className="text-green-700">In stock</span>:<span className="text-red-600">Out</span>}</td><td className="px-5 py-4"><button disabled={m.isPending} onClick={()=>m.mutate({id:p.productId,price:Number(f.price),salePrice:Number(f.salePrice),stock:Number(f.stock)})} className="rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white">Save</button></td></tr>}
export function VendorOrders(){const [page,setPage]=useState(0);const q=useQuery({queryKey:['vendor-orders',page],queryFn:()=>get<Page<any>>(`/vendor/orders?page=${page}&size=20`)});return <><PageHeader title="Vendor orders" subtitle="Read-only visibility into orders containing your products."/><Card>{q.isLoading?<Skeleton className="m-5 h-14"/>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<Table headers={['Order','Status','Created','Your line items']} rows={(q.data?.content||[]).map(o=>[`#${o.orderId}`,<Status key="s" value={o.status}/>,new Date(o.createdAt).toLocaleString(),<div key="i" className="space-y-1">{o.items.map((i:any)=><div key={i.productId} className="text-xs"><b>{i.name}</b> × {i.quantity} · ₹{Number(i.itemTotal).toLocaleString('en-IN')}</div>)}</div>])}/>}<div className="flex justify-between border-t p-4"><Button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="py-2 text-sm text-gray-500">Page {page+1} / {q.data?.totalPages||1}</span><Button disabled={!q.data||page+1>=q.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></Card></>}
export function Blocked({title,reason,endpoint}:{title:string;reason:string;endpoint?:string}){return <><PageHeader title={title} subtitle="UI surface intentionally held from fake data."/><Card className="max-w-3xl border-amber-200 bg-amber-50 p-7"><div className="flex gap-4"><AlertTriangle className="shrink-0 text-amber-600"/><div><h2 className="font-black">Blocked by backend capability</h2><p className="mt-2 text-sm leading-6 text-amber-900">{reason}</p>{endpoint&&<code className="mt-3 block rounded-lg bg-white/70 p-3 text-xs">{endpoint}</code>}</div></div></Card></>}

export function VendorPurchaseOrders(){
  const q=useQuery({queryKey:['vendor-purchase-orders'],queryFn:()=>get<any[]>('/vendor/purchase-orders')});
  const qc=useQueryClient();
  const mutation=useMutation({mutationFn:({id,action}:{id:number;action:'accept'|'reject'})=>put(`/vendor/purchase-orders/${id}/${action}`),onSuccess:()=>qc.invalidateQueries({queryKey:['vendor-purchase-orders']})});
  return <><PageHeader title="Purchase orders" subtitle="First-party replenishment orders created from warehouse stock thresholds."/><Card className="overflow-hidden">{q.isLoading?<Skeleton className="m-5 h-14"/>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<div className="divide-y divide-line">{(q.data||[]).map((po:any)=><PurchaseOrderRow key={po.id} po={po} busy={mutation.isPending} onAction={(action)=>mutation.mutate({id:po.id,action})}/>)}{!q.data?.length&&<div className="p-10 text-center text-sm text-gray-500">No purchase orders.</div>}</div>}</Card></>
}

function PurchaseOrderRow({po,busy,onAction}:{po:any;busy:boolean;onAction:(action:'accept'|'reject')=>void}){
  const [dispatch,setDispatch]=useState({vehicleNumber:'',driverName:'',driverPhone:''});
  const qc=useQueryClient();
  const d=useMutation({mutationFn:()=>put(`/vendor/purchase-orders/${po.id}/dispatch`,dispatch),onSuccess:()=>qc.invalidateQueries({queryKey:['vendor-purchase-orders']})});
  return <div className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-gray-400">PO #{po.id} · Store #{po.storeId}</div><div className="mt-1 text-lg font-black">{po.productName} × {po.quantity}</div><div className="mt-1 text-sm text-gray-500">{po.storeName||'Store'} · {po.status}</div>{po.note&&<div className="mt-1 text-xs text-gray-500">{po.note}</div>}</div>{po.status==='PENDING'&&<div className="flex gap-2"><Button disabled={busy} onClick={()=>onAction('accept')}>Accept</Button><button disabled={busy} onClick={()=>onAction('reject')} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700">Reject</button></div>}</div>{po.status==='ACCEPTED'&&<div className="mt-4 grid gap-3 md:grid-cols-4"><input aria-label="Vehicle number" value={dispatch.vehicleNumber} onChange={e=>setDispatch({...dispatch,vehicleNumber:e.target.value})} placeholder="Vehicle number" className="rounded-xl border px-3 py-2"/><input aria-label="Driver name" value={dispatch.driverName} onChange={e=>setDispatch({...dispatch,driverName:e.target.value})} placeholder="Driver name" className="rounded-xl border px-3 py-2"/><input aria-label="Driver phone" value={dispatch.driverPhone} onChange={e=>setDispatch({...dispatch,driverPhone:e.target.value})} placeholder="Driver phone" className="rounded-xl border px-3 py-2"/><Button disabled={d.isPending||!dispatch.vehicleNumber.trim()||!dispatch.driverName.trim()||!dispatch.driverPhone.trim()} onClick={()=>d.mutate()}>{d.isPending?'Dispatching…':'Dispatch PO'}</Button></div>}</div>
}

export function WarehousePurchaseOrders(){
  const q=useQuery({queryKey:['warehouse-purchase-orders'],queryFn:()=>get<any[]>('/warehouse/purchase-orders')});
  const qc=useQueryClient();
  const m=useMutation({mutationFn:({id,qty}:{id:number;qty:number})=>put(`/warehouse/purchase-orders/${id}/receive`,{receivedQuantity:qty}),onSuccess:()=>qc.invalidateQueries({queryKey:['warehouse-purchase-orders']})});
  return <><PageHeader title="Purchase orders" subtitle="Receive dispatched vendor stock and credit the warehouse inventory."/><Card className="overflow-hidden">{q.isLoading?<Skeleton className="m-5 h-14"/>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<div className="divide-y divide-line">{(q.data||[]).map((po:any)=><div key={po.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-gray-400">PO #{po.id} · Store #{po.storeId}</div><div className="mt-1 text-lg font-black">{po.productName} × {po.quantity}</div><div className="mt-1 text-sm text-gray-500">Vendor order status: {po.status}</div></div>{po.status==='DISPATCHED'&&<ReceiveForm po={po} busy={m.isPending} onReceive={(qty)=>m.mutate({id:po.id,qty})}/>}</div></div>)}{!q.data?.length&&<div className="p-10 text-center text-sm text-gray-500">No purchase orders awaiting warehouse action.</div>}</div>}</Card></>
}
function ReceiveForm({po,busy,onReceive}:{po:any;busy:boolean;onReceive:(qty:number)=>void}){const [qty,setQty]=useState(String(po.quantity)); const valid=Number.isInteger(Number(qty))&&Number(qty)>0&&Number(qty)<=po.quantity; return <div className="flex gap-2"><input aria-label={`Received quantity for purchase order ${po.id}`} value={qty} onChange={e=>setQty(e.target.value)} className="w-24 rounded-xl border px-3 py-2"/><Button disabled={busy||!valid} onClick={()=>onReceive(Number(qty))}>{busy?'Receiving…':'Receive stock'}</Button></div>}


export function AdminSeed(){
  const [message,setMessage]=useState<string>('');
  const mutation=useMutation({
    mutationFn:()=>post<string>('/admin/seed'),
    onSuccess:(result)=>setMessage(result||'Demo data seeded successfully.'),
    onError:(error)=>setMessage((error as Error).message||'Seeding failed.')
  });
  return <><PageHeader title="Seed demo data" subtitle="Development-only convenience for populating a fresh local database."/>
    <Card className="max-w-2xl p-6">
      <p className="text-sm leading-6 text-gray-600">Populate the local development database with sample users, stores, categories, products and related demo records.</p>
      <div className="mt-5 flex items-center gap-3">
        <Button disabled={mutation.isPending} onClick={()=>{setMessage('');mutation.mutate()}}>{mutation.isPending?'Seeding…':'Seed demo data'}</Button>
        {message&&<span className="text-sm font-medium" role="status">{message}</span>}
      </div>
    </Card>
  </>
}
