'use client';import * as React from 'react';import Link from 'next/link';import {usePathname,useRouter} from 'next/navigation';import {useState} from 'react';import {LayoutDashboard,Package,ShoppingCart,Warehouse,Users,Store,Truck,LogOut,Menu,ChevronRight,AlertTriangle,RefreshCw,ShieldAlert,ClipboardCheck,MessageCircleQuestion,BarChart3} from 'lucide-react';
export function Button({children,...p}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className="focus-ring rounded-xl theme-primary-bg px-4 py-2.5 text-sm font-semibold transition hover:-translate-y-px hover:shadow-soft disabled:cursor-not-allowed disabled:opacity-50" {...p}>{children}</button>}
export function Card({children,className='' }:{children:React.ReactNode,className?:string}){return <div className={`rounded-2xl border theme-border theme-surface theme-text shadow-soft ${className}`}>{children}</div>}
export function Skeleton({className=''}){return <div className={`animate-pulse rounded-lg bg-gray-200 ${className}`}/>}
export function ErrorState({message,onRetry}:{message:string,onRetry:()=>void}){return <Card className="p-8 text-center"><AlertTriangle className="mx-auto mb-3"/><h3 className="font-bold">Something went wrong</h3><p className="mx-auto mt-1 max-w-lg text-sm text-gray-500">{message}</p><button onClick={onRetry} className="mt-4 inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><RefreshCw size={15}/> Retry</button></Card>}
export function Dialog({open,title,children,onClose,className='' }:{open:boolean;title:string;children:React.ReactNode;onClose:()=>void;className?:string}){
  const ref=React.useRef<HTMLDivElement>(null);
  React.useEffect(()=>{
    if(!open)return;
    const previous=document.activeElement as HTMLElement|null;
    const root=ref.current;
    const focusables=()=>Array.from(root?.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')??[]).filter(x=>!x.hasAttribute('disabled'));
    focusables()[0]?.focus();
    const onKey=(e:KeyboardEvent)=>{
      if(e.key==='Escape'){e.preventDefault();onClose();return;}
      if(e.key!=='Tab')return;
      const f=focusables(); if(!f.length)return;
      const first=f[0],last=f[f.length-1];
      if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
      else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
    };
    document.addEventListener('keydown',onKey);
    return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};
  },[open,onClose]);
  if(!open)return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-5" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="dialog-title" className={`w-full ${className}`}><div className="theme-surface theme-text rounded-2xl border theme-border shadow-soft">{children}</div></div></div>;
}

const nav={admin:[['/admin','Overview',LayoutDashboard],['/admin/orders','Orders',ShoppingCart],['/admin/products','Products',Package],['/admin/users','Users',Users],['/admin/stores','Stores',Store],['/admin/vendors','Vendors',Truck],['/admin/fraud-reviews','Fraud reviews',ShieldAlert],['/admin/vendor-reviews','Vendor reviews',ClipboardCheck],['/admin/ask-policy','Ask Policy',MessageCircleQuestion],['/admin/ask-data','Ask Data',BarChart3],['/admin/seed','Seed data',RefreshCw]],warehouse:[['/warehouse','Pick queue',Warehouse],['/warehouse/stock','Stock',Package],['/warehouse/purchase-orders','Purchase orders',ClipboardCheck]],vendor:[['/vendor','Overview',LayoutDashboard],['/vendor/products','Products',Package],['/vendor/orders','Orders',ShoppingCart],['/vendor/purchase-orders','Purchase orders',ClipboardCheck]]} as const;
export function Shell({role,children}:{role:'admin'|'warehouse'|'vendor';children:React.ReactNode}){const path=usePathname();const router=useRouter();const [open,setOpen]=useState(false);const items=nav[role];const label=role==='warehouse'?'Warehouse manager':role[0].toUpperCase()+role.slice(1);return <div className="min-h-screen lg:flex"><aside className={`${open?'fixed inset-0 z-40':'hidden'} w-72 shrink-0 border-r border-line bg-white lg:sticky lg:top-0 lg:block lg:h-screen`}><div className="flex h-full flex-col p-5"><div className="mb-8 flex items-center justify-between"><div><div className="text-xl font-black tracking-tight">Near<span className="text-leaf">Now</span></div><div className="text-xs text-gray-400">Operations portal</div></div><button aria-label="Close navigation" className="lg:hidden" onClick={()=>setOpen(false)}>×</button></div><div className="mb-4 rounded-2xl bg-mint p-3"><div className="text-xs font-semibold uppercase tracking-wider text-leaf">Signed in as</div><div className="mt-1 font-bold">{label}</div></div><nav className="space-y-1">{items.map(([href,text,Icon])=><Link onClick={()=>setOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${path===href?'bg-ink text-white':'text-gray-600 hover:bg-gray-100'}`}><Icon size={18}/>{text}<ChevronRight className="ml-auto opacity-40" size={15}/></Link>)}</nav><div className="mt-auto"><button onClick={async()=>{await fetch('/api/session/logout',{method:'POST'});router.push('/login')}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-gray-500 hover:bg-gray-100"><LogOut size={18}/>Sign out</button></div></div></aside><main className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line glass px-5 lg:px-8"><button aria-label="Open navigation" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="text-sm font-semibold text-gray-500">{label} workspace</div><div className="h-8 w-8 rounded-full bg-lime"/></header><div className="mx-auto max-w-[1500px] p-5 lg:p-8">{children}</div></main></div>}
export function PageHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-3xl font-black tracking-tight">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-gray-500">{subtitle}</p>}</div>{action}</div>}
